import { QuickAdd } from '../components/common/QuickAdd'
import { TaskPreview } from '../components/dashboard/TaskPreview'

export function DashboardPage() {
  return <div className="dashboard">
    <section className="welcome-row"><div><p className="eyebrow">Thursday, August 20, 2026</p><h1>Good morning, Abhishek <span>✦</span></h1><p className="muted">Make today count, one small step at a time.</p></div><QuickAdd /></section>
    <section className="stats-grid"><div className="stat-card accent-card"><span className="stat-icon">✓</span><div><strong>12</strong><span>Tasks this week</span></div><small>↑ 18% <em>vs last week</em></small></div><div className="stat-card"><span className="stat-icon purple">◷</span><div><strong>4</strong><span>Reminders today</span></div><small>Next in 2h 15m</small></div><div className="stat-card"><span className="stat-icon orange">₹</span><div><strong>₹2,450</strong><span>Money to settle</span></div><small>3 people</small></div></section>
    <div className="dashboard-grid"><section className="panel tasks-panel"><div className="panel-heading"><div><h2>Today <span className="count-pill">4</span></h2><p className="muted">Thursday, August 20</p></div><button className="text-button">View all →</button></div><div className="task-list"><TaskPreview title="Call Rahul about the project" time="5:00 PM" tag="Work" color="#5b67e8" /><TaskPreview title="Finish the quarterly report" tag="Work" color="#5b67e8" /><TaskPreview title="Pick up groceries" time="7:30 PM" tag="Personal" color="#e68b3d" /><TaskPreview title="Pay electricity bill" tag="Finance" color="#38a58c" /></div><button className="add-task-line">+ Add a task</button></section><section className="panel"><div className="panel-heading"><div><h2>Upcoming</h2><p className="muted">Your next few days</p></div><button className="text-button">Calendar ↗</button></div><div className="upcoming-list"><div><time>FRI<strong>21</strong></time><p><strong>Send client proposal</strong><small>Tomorrow · 10:00 AM</small></p></div><div><time>SAT<strong>22</strong></time><p><strong>Team offsite</strong><small>Saturday · All day</small></p></div><div><time>MON<strong>25</strong></time><p><strong>Rent payment</strong><small>Monday · 9:00 AM</small></p></div></div></section></div>
    <section className="insight-card"><span className="insight-icon">✦</span><div><strong>Quickplan insight</strong><p>You have a lighter afternoon. It could be a good time to finish your quarterly report.</p></div><button className="dismiss-button">×</button></section>
  </div>
}
